{
 "title": "Duplicati Backup Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "backup_name",
    "query": {
     "query": "label_values(duplicati_backup_ops_total,backup_name)"
    }
   },
   {
    "name": "operation",
    "label": "operation",
    "query": {
     "query": "label_values(duplicati_backup_ops_total,operation_name)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, free_quota_space{backup_name=\"$backup_name\", operation_name=\"$operation\"}) / topk(1, total_quota_space{backup_name=\"$backup_name\", operation_name=\"$operation\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$backup_name versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_list_count{backup_name=\"$backup_name\", operation_name=\"Backup\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total $operation Success [$backup_name]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicati_backup_ops_total{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total $operation Failed [$backup_name]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicati_backup_ops_total{backup_name=\"$backup_name\", result=\"Fail\", operation_name=\"$operation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$backup_name total operation",
   "type": "stat",
   "description": "Backups and restore",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(duplicati_backup_ops_total{backup_name=\"$backup_name\", operation_name=\"Backup\"})\n+ sum(duplicati_backup_ops_total{backup_name=\"$backup_name\", operation_name=\"Restore\"} OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$operation duration [$backup_name]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, duration{backup_name=\"$backup_name\", operation_name=\"$operation\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "$backup_name folders created over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "folders_created{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "Folders Created"
    }
   ]
  },
  {
   "title": "$backup_name bytes I/O over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "bytes_uploaded{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "Bytes upload"
    },
    {
     "expr": "bytes_downloaded{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "Bytes download"
    }
   ]
  },
  {
   "title": "$backup_name files deleted over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "files_deleted{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "Files deleted"
    }
   ]
  },
  {
   "title": "$backup_name files upload over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "files_uploaded{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "Files upload"
    },
    {
     "expr": "files_downloaded{backup_name=\"$backup_name\", operation_name=\"$operation\", result=\"Success\"}",
     "legendFormat": "Files download"
    }
   ]
  }
 ]
}