{
 "title": "Duplicati Backup Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "backup_name", "query": { "query": "label_values(backup_name)" } },
   { "name": "operation", "query": { "query": "label_values(operation_name)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, free_quota_space{backup_name=\"$backup_name\"}) / topk(1, total_quota_space{backup_name=\"$backup_name\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$backup_name versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_list_count{backup_name=\"$backup_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total backup Success [$backup_name]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicati_backup_ops_total{backup_name=\"$backup_name\", result=\"Success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Backup Failed [$backup_name]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicati_backup_ops_total{backup_name=\"$backup_name\", result=\"Fail\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$backup_name total operation",
   "type": "stat",
   "description": "Backups and restore",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicati_backup_ops_total{backup_name=\"$backup_name\", operation_name=\"$operation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$backup_name duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duration{backup_name=\"$backup_name\"}",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "$backup_name folders created over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "folders_created{backup_name=\"$backup_name\"}",
     "legendFormat": "Folders Created"
    }
   ]
  },
  {
   "title": "$backup_name bytes I/O over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "bytes_uploaded{backup_name=\"$backup_name\"}",
     "legendFormat": "Bytes upload"
    },
    {
     "expr": "bytes_downloaded{backup_name=\"$backup_name\"}",
     "legendFormat": "Bytes download"
    }
   ]
  },
  {
   "title": "$backup_name files deleted over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "files_deleted{backup_name=\"$backup_name\"}",
     "legendFormat": "Files deleted"
    }
   ]
  },
  {
   "title": "$backup_name files upload over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "files_uploaded{backup_name=\"$backup_name\"}",
     "legendFormat": "Files upload"
    },
    {
     "expr": "files_downloaded{backup_name=\"$backup_name\"}",
     "legendFormat": "Files download"
    }
   ]
  }
 ]
}